//form
export const POST_RESERVE = "POST_RESERVE";
export const POST_RESERVE_ERROR = "POST_RESERVE_ERROR";

//review
export const ADD_REVIEW = "ADD_REVIEW";
export const GET_REVIEWS = "GET_REVIEWS";

export const FETCH_DOCTOR_REQUEST = "FETCH_DOCTOR_REQUEST";
export const FETCH_DOCTOR_SUCCESS = "FETCH_DOCTOR_SUCCESS";
export const FETCH_DOCTOR_FAILURE = "FETCH_DOCTOR_FAILURE";
