export const POST_RESERVE = "POST_RESERVE";
export const POST_RESERVE_ERROR = "POST_RESERVE_ERROR";
export const FORM_DATA = "FORM_DATA";
export const GET_DOCTOR = "GET_DOCTOR";
export const CLEAN_DATAIL_ID = "CLEAN_DATAIL_ID"
export const GET_ESPECIALIDADES = "GET_ESPECIALIDADES"
